/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllControlador.ControladorSuporte;

/**
 *
 * @author Felly
 */
public class TelaRemoverServicoBasico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRemoverServicoBasico
     */
    public TelaRemoverServicoBasico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNomedoDono = new javax.swing.JTextField();
        jConsultCliente = new javax.swing.JButton();
        jIDdoAnimal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jNomedoDono1 = new javax.swing.JTextField();
        jCPFDonoAlterar = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jServicosAdquiridos = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jidCompra = new javax.swing.JTextField();
        jBuscarID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jNomeCompra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jidproduto = new javax.swing.JTextField();
        jdeletCompra = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cliente e Animal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel6.setText("Código do Animal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 20));

        jLabel9.setText("Nome:");
        jLabel9.setToolTipText("");
        jLabel9.setName(""); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 40, 20));

        jNomedoDono.setEditable(false);
        getContentPane().add(jNomedoDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 190, -1));

        jConsultCliente.setText("Consultar Animal");
        jConsultCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));
        getContentPane().add(jIDdoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 70, -1));

        jLabel10.setText("Animal:");
        jLabel10.setToolTipText("");
        jLabel10.setName(""); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 50, 20));

        jNomedoDono1.setEditable(false);
        getContentPane().add(jNomedoDono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 110, -1));

        jCPFDonoAlterar.setEditable(false);
        try {
            jCPFDonoAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jCPFDonoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 140, -1));

        jLabel11.setText("CPF:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dados do Animal:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Remover serviço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 630, 49));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 750, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Serviço Adquiridos:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jServicosAdquiridos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Serviço", "CPF", "ID Animal", "Nome", "Informação", "Data&Hora", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jServicosAdquiridos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 740, 100));

        jSeparator4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 820, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Remover Serviço:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("ID Serviço:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 30));

        jidCompra.setEditable(false);
        jidCompra.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jidCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 50, 30));

        jBuscarID.setText("@");
        jBuscarID.setEnabled(false);
        jBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(jBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, 30));

        jLabel8.setText("Nome:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, 20));

        jNomeCompra.setEditable(false);
        jNomeCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jNomeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 170, -1));

        jLabel15.setText("Data&Hora:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 70, 20));

        jidproduto.setEditable(false);
        jidproduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jidproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 150, -1));

        jdeletCompra.setText("Deletar");
        jdeletCompra.setEnabled(false);
        jdeletCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jdeletCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 130, -1));

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 130, -1));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas NetBeans\\proje00235ety\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jLabel16.setToolTipText(""); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jDesktopPane1.add(jLabel16);
        jLabel16.setBounds(0, 0, 900, 580);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jConsultClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultClienteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultClienteActionPerformed

    private void jBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarIDActionPerformed
        /*String cpf = jCPFAnimalAlterar.getText();
        int posicao = Integer.parseInt(jidCompra.getText());
        CompraProduto exibirCompra = ControladorCompraProduto.exibirCompra(cpf, posicao);
        if (exibirCompra != null) {
            jBuscarID.setEnabled(false);
            jidCompra.setEditable(false);
            jNomeCompra.setEditable(true);
            jidproduto.setEditable(true);
            jdeletCompra.setEnabled(true);
            jNomeCompra.setText(exibirCompra.getNomeCompra());
            jidproduto.setText(exibirCompra.getDataCompra());
        }*/

        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarIDActionPerformed

    private void jdeletCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletCompraActionPerformed
       /* String cpf = jCPFAnimalAlterar.getText();
        int posicao = Integer.parseInt(jidCompra.getText());

        if (RepositorioCompra.setRemoverCompra(cpf, posicao)) {
            jNomeCompra.setEditable(false);
            jidproduto.setEditable(false);
            jNomeCompra.setText("");
            jidproduto.setText("");
            jdeletCompra.setEnabled(false);
            jidCompra.setEditable(true);
            jBuscarID.setEnabled(true);
        }

        Object[] colunas = {"ID Compra", "Nome", "Valor", "ID Produto", "Data&Hora", "Quantidade"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(colunas);
        jTableRemoverCompra.setModel(modelo);
        for (int i = 0; i < BancoListCompra.size(); i++) {
            CompraProduto c = BancoListCompra.get(i);
            if (c.getCPFCompra().equals(cpf)) {
                modelo.addRow(new String[]{c.getCodigoCompra() + "",
                    c.getNomeCompra(),
                    c.getValorCompra() + "",
                    c.getCodigoProduto() + "",
                    c.getDataCompra(),
                    c.getQuantidadeC() + ""});
        }
        }
        jTableRemoverCompra.setModel(modelo);

        //Deletar*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jdeletCompraActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuscarID;
    private javax.swing.JFormattedTextField jCPFDonoAlterar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JButton jConsultCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jIDdoAnimal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeCompra;
    private javax.swing.JTextField jNomedoDono;
    private javax.swing.JTextField jNomedoDono1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jServicosAdquiridos;
    private javax.swing.JButton jdeletCompra;
    private javax.swing.JTextField jidCompra;
    private javax.swing.JTextField jidproduto;
    // End of variables declaration//GEN-END:variables
}
