/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.Repositorio.RepositorioCliente;
import AllSuporte.Suporte;
import AllSuporte.ValidarDados;
import javax.swing.JOptionPane;

/**
 *
 * @author Felly
 */
public class TelaAlterarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarCliente
     */
    public TelaAlterarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGroupAltCliente = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRemoverC = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jConsultClienteAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSexo1C = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jNomeAlterarC = new javax.swing.JTextField();
        jSexo2C = new javax.swing.JRadioButton();
        jCPFDonoAlterar = new javax.swing.JFormattedTextField();
        jTelefoneAlterar = new javax.swing.JFormattedTextField();
        jAlterarC = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Alterando Cliente");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Alterar CLIENTE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 629, 49));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Dados do Cliente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jRemoverC.setText("Remover");
        jRemoverC.setEnabled(false);
        jRemoverC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverCActionPerformed(evt);
            }
        });
        getContentPane().add(jRemoverC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 125, -1));

        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jConsultClienteAlterar.setText("Consultar Cliente");
        jConsultClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultClienteAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultClienteAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jGroupAltCliente.add(jSexo1C);
        jSexo1C.setText("Homem");
        jSexo1C.setEnabled(false);
        jSexo1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexo1CActionPerformed(evt);
            }
        });
        getContentPane().add(jSexo1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Informações do Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 125, -1));

        jLabel6.setText("CPF do Cliente:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jNomeAlterarC.setEnabled(false);
        getContentPane().add(jNomeAlterarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 262, -1));

        jGroupAltCliente.add(jSexo2C);
        jSexo2C.setText("Mulher");
        jSexo2C.setEnabled(false);
        getContentPane().add(jSexo2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        try {
            jCPFDonoAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jCPFDonoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 140, -1));

        try {
            jTelefoneAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTelefoneAlterar.setEnabled(false);
        getContentPane().add(jTelefoneAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 163, -1));

        jAlterarC.setText("Alterar");
        jAlterarC.setEnabled(false);
        jAlterarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarCActionPerformed(evt);
            }
        });
        getContentPane().add(jAlterarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 125, -1));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas Java\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jLabel2.setToolTipText(""); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConsultClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultClienteAlterarActionPerformed

        String cpf;
        cpf = jCPFDonoAlterar.getText();
        if (RepositorioCliente.setValidarCPF(cpf)) {
            jNomeAlterarC.setEnabled(true);
            jTelefoneAlterar.setEnabled(true);
            jSexo1C.setEnabled(true);
            jAlterarC.setEnabled(true);
            jSexo2C.setEnabled(true);
            jRemoverC.setEnabled(true);
            jCPFDonoAlterar.setEnabled(false);
            jNomeAlterarC.setText(RepositorioCliente.clientes.getNome());
            jTelefoneAlterar.setText(RepositorioCliente.clientes.getTelefone());

            if (RepositorioCliente.clientes.getSexo().equals("Homem")) {
                jSexo1C.setSelected(true);
                //Homem
            } else {
                jSexo2C.setSelected(true);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultClienteAlterarActionPerformed

    private void jRemoverCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverCActionPerformed

        String cpf;
        cpf = jCPFDonoAlterar.getText();
        if (RepositorioCliente.setRemoverCliente(cpf)) {
            JOptionPane.showMessageDialog(null, "Cliente removido com sucesso!!!");
            this.dispose();
        }

        //Remover
        // TODO add your handling code here:
    }//GEN-LAST:event_jRemoverCActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jSexo1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexo1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSexo1CActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Suporte.setMudarStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jAlterarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarCActionPerformed

        String nome = "";
        String telefone;
        String sexoC = "";
        String cErros = "!-Preenchimento Incorreto-!\n";
        boolean testCadastro = true;

        if ("".equals(jNomeAlterarC.getText())) {
            cErros += "* Nome\n";
            testCadastro = false;
        }

        telefone = jTelefoneAlterar.getText();
        if (!ValidarDados.validarTelefone(telefone)) {
            cErros += "* Telefone\n";
            testCadastro = false;
        }

        if (jSexo1C.isSelected() == true) {
            sexoC = jSexo1C.getText();
        }
        if (jSexo2C.isSelected() == true) {
            sexoC = jSexo2C.getText();
        }

        if ("".equals(sexoC)) {
            testCadastro = false;
            cErros += "* Selecione o Sexo\n";
        }

        if (testCadastro) {
            nome = jNomeAlterarC.getText();
            telefone = jTelefoneAlterar.getText();
            String cpf = jCPFDonoAlterar.getText();
            int resp = JOptionPane.showConfirmDialog(null, "Confirma Alteração?");
            if (resp == 0) {
                if (RepositorioCliente.setAlterarCliente(nome, cpf, telefone, sexoC)) {
                    JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!!!");
                } else {
                    JOptionPane.showMessageDialog(null, cErros);
                }
            }
        }

//Alterar
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlterarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlterarC;
    private javax.swing.JFormattedTextField jCPFDonoAlterar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JButton jConsultClienteAlterar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.ButtonGroup jGroupAltCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNomeAlterarC;
    private javax.swing.JButton jRemoverC;
    private javax.swing.JRadioButton jSexo1C;
    private javax.swing.JRadioButton jSexo2C;
    private javax.swing.JFormattedTextField jTelefoneAlterar;
    // End of variables declaration//GEN-END:variables
}
