/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.ServicoBasico;
import AllControlador.ControladorServicoBasico;
import AllControlador.ControladorSuporte;
import javax.swing.JOptionPane;

/**
 *
 * @author Felly
 */
public class TelaCadastroServicoBasico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroServicoBasico
     */
    public TelaCadastroServicoBasico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jNomeCadastroServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInformacoes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCodigoServico = new javax.swing.JTextField();
        jCadastrarServico = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("CADASTRO serviço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 650, 49));

        jLabel1.setText("Nome do Serviço:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        getContentPane().add(jNomeCadastroServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 174, -1));

        jLabel2.setText("Informações:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jInformacoes.setColumns(20);
        jInformacoes.setRows(5);
        jScrollPane1.setViewportView(jInformacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 293, 81));

        jLabel6.setText("Valor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 20));
        getContentPane().add(jValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 128, -1));

        jLabel4.setText("Codigo de Barra:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, 20));
        getContentPane().add(jCodigoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 128, -1));

        jCadastrarServico.setText("Cadastrar");
        jCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jCadastrarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 164, -1));

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 144, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas NetBeans\\proje00235ety\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarServicoActionPerformed

        String nomep;
        String inforp;
        double valorp;
        int codigoP;

        nomep = jNomeCadastroServico.getText();
        inforp = jInformacoes.getText();
        valorp = Double.parseDouble(jValor.getText());
        codigoP = Integer.parseInt(jCodigoServico.getText());

        ServicoBasico cadServico = new ServicoBasico(nomep, inforp, valorp, codigoP);
        String testCadastroServico = ControladorServicoBasico.cadastrarSercico(cadServico);
        if (testCadastroServico.equals("1")) {
            jNomeCadastroServico.setText("");
            jInformacoes.setText("");
            jValor.setText("");
            jCodigoServico.setText("");
        } else {
            JOptionPane.showMessageDialog(null, testCadastroServico);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jCadastrarServicoActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCadastrarServico;
    private javax.swing.JButton jCancelar;
    private javax.swing.JTextField jCodigoServico;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextArea jInformacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomeCadastroServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
