/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.ServicoBasico;
import AllControlador.ControladorServicoBasico;
import AllControlador.ControladorSuporte;
import javax.swing.JOptionPane;

/**
 *
 * @author Felly
 */
public class TelaAlterarServicoBasico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarServicoBasico
     */
    public TelaAlterarServicoBasico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jConsultServicoAlterar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jNomeAlterarServico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInformacoes = new javax.swing.JTextArea();
        jValor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jAlterarServico = new javax.swing.JButton();
        jdeletServico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Alterar Serviço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 610, 49));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 740, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Pesquisar Serviço:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 30));
        getContentPane().add(jcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 141, 30));

        jLabel6.setText("Código:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 30));

        jConsultServicoAlterar.setText("Consultar Serviço");
        jConsultServicoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultServicoAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultServicoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 770, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Dados do Serviço:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        jLabel1.setText("Nome do Serviço:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jNomeAlterarServico.setEditable(false);
        getContentPane().add(jNomeAlterarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 174, -1));

        jLabel13.setText("Informações:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jInformacoes.setEditable(false);
        jInformacoes.setColumns(20);
        jInformacoes.setRows(5);
        jScrollPane1.setViewportView(jInformacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 293, 81));

        jValor.setEditable(false);
        getContentPane().add(jValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 128, -1));

        jLabel15.setText("Valor:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 20));

        jAlterarServico.setText("Alterar");
        jAlterarServico.setEnabled(false);
        jAlterarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jAlterarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 130, -1));

        jdeletServico.setText("Deletar");
        jdeletServico.setEnabled(false);
        jdeletServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jdeletServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 130, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 130, -1));

        jSeparator5.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 690, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas NetBeans\\proje00235ety\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jLabel4.setToolTipText(""); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jConsultServicoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultServicoAlterarActionPerformed

        int cod = Integer.parseInt(jcodigo.getText());

        ServicoBasico exibeServico = ControladorServicoBasico.exibirServico(cod);
        if (exibeServico != null) {
            jcodigo.setEditable(false);
            jConsultServicoAlterar.setEnabled(false);
            jNomeAlterarServico.setEditable(true);
            jInformacoes.setEditable(true);
            jValor.setEditable(true);
            jAlterarServico.setEnabled(true);
            jdeletServico.setEnabled(true);
            jNomeAlterarServico.setText(exibeServico.getS_NomeS());
            jInformacoes.setText(exibeServico.getS_InforS());
            jValor.setText(Double.toString(exibeServico.getS_ValorS()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultServicoAlterarActionPerformed

    private void jAlterarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarServicoActionPerformed
        String nomeP = "";
        String inforP = "";
        double valorP;
        int codigoP;

        nomeP = jNomeAlterarServico.getText();
        inforP = jInformacoes.getText();
        valorP = Double.parseDouble(jValor.getText());
        codigoP = Integer.parseInt(jcodigo.getText());

        ServicoBasico altServico = new ServicoBasico(nomeP, inforP, valorP, codigoP);

        String testAlterarServico = ControladorServicoBasico.editarServico(altServico);
        if (testAlterarServico.equals("1")) {
            jcodigo.setEditable(true);
            jcodigo.setText("");
            jConsultServicoAlterar.setEnabled(true);
            jNomeAlterarServico.setEditable(false);
            jNomeAlterarServico.setText("");
            jInformacoes.setEditable(false);
            jInformacoes.setText("");
            jValor.setEditable(false);
            jValor.setText("");
            jAlterarServico.setEnabled(false);
            jdeletServico.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, testAlterarServico);
        }

        //AlterarAnimal
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlterarServicoActionPerformed

    private void jdeletServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletServicoActionPerformed

        int codigoP = Integer.parseInt(jcodigo.getText());
        String testRemoverServico = ControladorServicoBasico.removerProduto(codigoP);
        if (testRemoverServico.equals("1")) {
            jcodigo.setEditable(true);
            jcodigo.setText("");
            jConsultServicoAlterar.setEnabled(true);
            jNomeAlterarServico.setEditable(false);
            jNomeAlterarServico.setText("");
            jInformacoes.setEditable(false);
            jInformacoes.setText("");
            jValor.setEditable(false);
            jValor.setText("");
            jAlterarServico.setEnabled(false);
            jdeletServico.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, testRemoverServico);
        }

        //Deletar
        // TODO add your handling code here:
    }//GEN-LAST:event_jdeletServicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlterarServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jConsultServicoAlterar;
    private javax.swing.JTextArea jInformacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeAlterarServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jValor;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JButton jdeletServico;
    // End of variables declaration//GEN-END:variables
}
