/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.Repositorio.RepositorioEstoque;
import AllClass.Repositorio.RepositorioProduto;
import AllControlador.ControladorEstoque;
import AllSuporte.Suporte;

/**
 *
 * @author Felly
 */
public class TelaEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jescolhasadd = new javax.swing.ButtonGroup();
        jCodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCancelarExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jQuantMais = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jQuantMenos = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jValorAtual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jNomeProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jNovoValor = new javax.swing.JTextField();
        jBuscarProduto = new javax.swing.JButton();
        jSalvarEstoque = new javax.swing.JButton();
        jRemover = new javax.swing.JRadioButton();
        jAdd = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCodigoProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, 30));

        jLabel4.setText("Codigo de Barra:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 100, 30));

        jCancelarExit.setText("Cancelar");
        jCancelarExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarExitActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelarExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 90, 30));

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 50)); // NOI18N
        jLabel5.setText("Atualizando Estoque");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 650, 49));

        jQuantMais.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jQuantMais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jQuantMais.setEnabled(false);
        getContentPane().add(jQuantMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 70, 30));

        jLabel9.setText("Adicionar Quantidade:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, 30));

        jQuantMenos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jQuantMenos.setToolTipText("");
        jQuantMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jQuantMenos.setEnabled(false);
        getContentPane().add(jQuantMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 70, 30));

        jLabel10.setText("Remover Quantidade:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 30));

        jQuantidade.setEditable(false);
        jQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 60, 30));

        jLabel6.setText("Quantidade Atual:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, 30));

        jValorAtual.setEditable(false);
        jValorAtual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jValorAtual.setForeground(new java.awt.Color(0, 255, 0));
        jValorAtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jValorAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 150, 30));

        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 50, 30));

        jNomeProduto.setEditable(false);
        jNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 250, 30));

        jLabel11.setText("Valor Atual:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 70, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 900, 10));

        jLabel12.setText("Novo Valor:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 70, 30));

        jNovoValor.setEditable(false);
        jNovoValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNovoValor.setForeground(new java.awt.Color(0, 255, 0));
        jNovoValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jNovoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 150, 30));

        jBuscarProduto.setText("Buscar");
        jBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jBuscarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, 30));

        jSalvarEstoque.setText("Salvar");
        jSalvarEstoque.setEnabled(false);
        jSalvarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(jSalvarEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 100, 30));

        jRemover.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        jescolhasadd.add(jRemover);
        jRemover.setEnabled(false);
        jRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(jRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, 30));

        jAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("text"));
        jescolhasadd.add(jAdd);
        jAdd.setEnabled(false);
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });
        getContentPane().add(jAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, 30));

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(900, 600));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas Java\\PetshopSmart\\IMG\\TelaCadastro22.png")); // NOI18N
        jDesktopPane2.add(jLabel8);
        jLabel8.setBounds(0, 0, 900, 600);

        jDesktopPane1.add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        Suporte.setMudarStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jCancelarExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarExitActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarExitActionPerformed

    private void jBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarProdutoActionPerformed
        String codigo;
        codigo = jCodigoProduto.getText();
        if (RepositorioProduto.getValidarProduto(codigo)) {
            jCodigoProduto.setEditable(false);
            jNovoValor.setEditable(true);
            jSalvarEstoque.setEnabled(true);
            jAdd.setEnabled(true);
            jRemover.setEnabled(true);
            
            jNomeProduto.setText(RepositorioProduto.estoqueProduto.getNome());
            jQuantidade.setText(Integer.toString(RepositorioProduto.estoqueProduto.getQuantidade()));
            jValorAtual.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
            jNovoValor.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarProdutoActionPerformed

    private void jSalvarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarEstoqueActionPerformed
        int quantMais;
        int quantMenos;
        int codigo = Integer.parseInt(jCodigoProduto.getText());
        quantMais = (Integer) jQuantMais.getValue();
        quantMenos = (Integer) jQuantMenos.getValue();
        String xquantMenos = Integer.toString(quantMenos);
        double valor = Double.parseDouble(jNovoValor.getText());
        
        String testADDEstoque = ControladorEstoque.addEstoque(codigo, quantMais, valor);
        if (testADDEstoque.equals("1")) {
            jNomeProduto.setText(RepositorioProduto.estoqueProduto.getNome());
            jQuantidade.setText(Integer.toString(RepositorioProduto.estoqueProduto.getQuantidade()));
            jValorAtual.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
            jNovoValor.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
        }
        
        String testRemoveEstoque = ControladorEstoque.removeEstoque(codigo, quantMenos, valor);
        if ((quantMenos > 0) && (quantMenos <= RepositorioProduto.estoqueProduto.getQuantidade())) {
            if (testRemoveEstoque.equals("1")) {
                jNomeProduto.setText(RepositorioProduto.estoqueProduto.getNome());
                jQuantidade.setText(Integer.toString(RepositorioProduto.estoqueProduto.getQuantidade()));
                jValorAtual.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
                jNovoValor.setText(Double.toString(RepositorioProduto.estoqueProduto.getValorP()));
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jSalvarEstoqueActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        
        if (jAdd.isSelected() == true) {
            jQuantMais.setEnabled(true);
            jQuantMenos.setValue(0);
            jQuantMenos.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jAddActionPerformed

    private void jRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverActionPerformed
        
        if (jRemover.isSelected() == true) {
            jQuantMais.setEnabled(false);
            jQuantMenos.setEnabled(true);
            jQuantMais.setValue(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jAdd;
    private javax.swing.JButton jBuscarProduto;
    private javax.swing.JButton jCancelarExit;
    private javax.swing.JTextField jCodigoProduto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeProduto;
    private javax.swing.JTextField jNovoValor;
    private javax.swing.JSpinner jQuantMais;
    private javax.swing.JSpinner jQuantMenos;
    private javax.swing.JTextField jQuantidade;
    private javax.swing.JRadioButton jRemover;
    private javax.swing.JButton jSalvarEstoque;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jValorAtual;
    private javax.swing.ButtonGroup jescolhasadd;
    // End of variables declaration//GEN-END:variables
}
