/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.Cliente;
import AllControlador.ControladorSuporte;
import javax.swing.JOptionPane;

/**
 *
 * @author Felly
 */
public class TelaCadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelCadastroCliente
     */
    public TelaCadastroCliente() {
        //Organiza os Componentes no Formulario
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscolhaSexo = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jSexo1C = new javax.swing.JRadioButton();
        jSexo2C = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jNomeCadastroC = new javax.swing.JTextField();
        jCPF = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTelefone = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCadastrarC = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrando Cliente");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        setVisible(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Sexo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jEscolhaSexo.add(jSexo1C);
        jSexo1C.setText("Homem");
        jSexo1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexo1CActionPerformed(evt);
            }
        });
        getContentPane().add(jSexo1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        jEscolhaSexo.add(jSexo2C);
        jSexo2C.setText("Mulher");
        getContentPane().add(jSexo2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jNomeCadastroC.setToolTipText("Cliente Ex: \"Édypo Fellype Silva\"...");
        getContentPane().add(jNomeCadastroC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 262, -1));

        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setToolTipText("CPF Ex: \"000.000.000-00\"...");
        getContentPane().add(jCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, -1));

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        try {
            jTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTelefone.setToolTipText("Telefone Ex: \"(81)3333-3333\"...");
        getContentPane().add(jTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 163, -1));

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jCadastrarC.setText("Cadastrar");
        jCadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarCActionPerformed(evt);
            }
        });
        getContentPane().add(jCadastrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 125, -1));

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 125, -1));

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("CADASTRO CLIENTE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 75, 629, 49));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas Java\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSexo1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexo1CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSexo1CActionPerformed

    private void jCadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarCActionPerformed

        String nome="";
        String cpf="";
        String telefone="";
        String sexoC = "";
        
        nome = jNomeCadastroC.getText();
        cpf = jCPF.getText();
        telefone = jTelefone.getText();
        if (jSexo1C.isSelected() == true) {
            sexoC = jSexo1C.getText();
        }
        if (jSexo2C.isSelected() == true) {
            sexoC = jSexo2C.getText();
        }

        Cliente c = new Cliente(nome, cpf, telefone, sexoC);
        String testCadastroCliente = AllControlador.ControladorCliente.cadastroCliente(c);
        if(testCadastroCliente.equals("1")){
            jNomeCadastroC.setText("");
            jCPF.setText("");
            jTelefone.setText("");
        }else{
            JOptionPane.showMessageDialog(null, testCadastroCliente);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jCadastrarCActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JButton jCadastrarC;
    private javax.swing.JButton jCancelar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.ButtonGroup jEscolhaSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomeCadastroC;
    private javax.swing.JRadioButton jSexo1C;
    private javax.swing.JRadioButton jSexo2C;
    private javax.swing.JFormattedTextField jTelefone;
    // End of variables declaration//GEN-END:variables

}
