/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.Compra;
import AllControlador.ControladorCompra;
import AllControlador.ControladorSuporte;
import static BancoDeDados.BancoPetshop.BancoListCompra;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felly
 */
public class TelaRelatorioCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorioCompra
     */
    public TelaRelatorioCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCompra = new javax.swing.ButtonGroup();
        jCancelar = new javax.swing.JButton();
        jImprimir = new javax.swing.JButton();
        jTableClientes = new javax.swing.JScrollPane();
        jTableRelatorioCompra = new javax.swing.JTable();
        jRadioCpf = new javax.swing.JRadioButton();
        jCPFRelatorioCliente = new javax.swing.JFormattedTextField();
        jConsultarPorCPFCompra = new javax.swing.JButton();
        jRadioDataHora = new javax.swing.JRadioButton();
        jPesquisaCodigoProduto = new javax.swing.JTextField();
        jRadioAllCompras = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jConsultarPorDataHora = new javax.swing.JButton();
        jRadioCodigoProduto = new javax.swing.JRadioButton();
        jConsultarPorCodigoProduto = new javax.swing.JButton();
        jPesquisaDataHora = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCancelar.setText("Sair");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 90, -1));

        jImprimir.setText("Imprimir");
        jImprimir.setEnabled(false);
        getContentPane().add(jImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 530, 90, -1));

        jTableRelatorioCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"
            }
        ));
        jTableClientes.setViewportView(jTableRelatorioCompra);

        getContentPane().add(jTableClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 780, 240));

        buttonGroupCompra.add(jRadioCpf);
        jRadioCpf.setText("CPF:");
        jRadioCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 50, 30));

        try {
            jCPFRelatorioCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPFRelatorioCliente.setText("");
        jCPFRelatorioCliente.setEnabled(false);
        getContentPane().add(jCPFRelatorioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, 30));

        jConsultarPorCPFCompra.setText("@");
        jConsultarPorCPFCompra.setToolTipText("");
        jConsultarPorCPFCompra.setEnabled(false);
        jConsultarPorCPFCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarPorCPFCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultarPorCPFCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 30));

        buttonGroupCompra.add(jRadioDataHora);
        jRadioDataHora.setText("Data/Hora:");
        jRadioDataHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDataHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, 30));

        jPesquisaCodigoProduto.setToolTipText("Digite o nome que deseja pesquisar \"Ex: Edypo Fellype\"");
        jPesquisaCodigoProduto.setEnabled(false);
        jPesquisaCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisaCodigoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jPesquisaCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 30));

        buttonGroupCompra.add(jRadioAllCompras);
        jRadioAllCompras.setText("All Compras");
        jRadioAllCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAllComprasActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAllCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Relatório Compra");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jConsultarPorDataHora.setText("@");
        jConsultarPorDataHora.setToolTipText("");
        jConsultarPorDataHora.setEnabled(false);
        jConsultarPorDataHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarPorDataHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultarPorDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        buttonGroupCompra.add(jRadioCodigoProduto);
        jRadioCodigoProduto.setText("Código Produto:");
        jRadioCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCodigoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 30));

        jConsultarPorCodigoProduto.setText("@");
        jConsultarPorCodigoProduto.setToolTipText("");
        jConsultarPorCodigoProduto.setEnabled(false);
        jConsultarPorCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarPorCodigoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultarPorCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 30, 30));

        jPesquisaDataHora.setToolTipText("Digite o nome que deseja pesquisar \"Ex: Edypo Fellype\"");
        jPesquisaDataHora.setEnabled(false);
        jPesquisaDataHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisaDataHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jPesquisaDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 80, 30));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas Java\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jLabel13.setToolTipText(""); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jDesktopPane1.add(jLabel13);
        jLabel13.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jRadioCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCpfActionPerformed

        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);
        if (jRadioCpf.isSelected() == true) {
            //AtivaOProprio
            jRadioCpf.setEnabled(false);
            jCPFRelatorioCliente.setEnabled(true);
            jConsultarPorCPFCompra.setEnabled(true);
            //CodigoProduto
            jRadioCodigoProduto.setEnabled(true);
            jPesquisaCodigoProduto.setEnabled(false);
            jConsultarPorCodigoProduto.setEnabled(false);
            jPesquisaCodigoProduto.setText("");
            //Data&Hora
            jRadioDataHora.setEnabled(true);
            jPesquisaDataHora.setEnabled(false);
            jConsultarPorDataHora.setEnabled(false);
            jPesquisaDataHora.setText("");
            //AllCompras
            jRadioAllCompras.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCpfActionPerformed

    private void jConsultarPorCPFCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarPorCPFCompraActionPerformed

        String cpf = jCPFRelatorioCliente.getText();
        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        String testValidarCPFCompra = ControladorCompra.existeCPFCompra(cpf);
        if (testValidarCPFCompra.equals("1")) {
            for (int i = 0; i < BancoListCompra.size(); i++) {
                Compra compras = BancoListCompra.get(i);
                if (compras.getCPFCompra().equals(cpf)) {
                    modeloTableCompra.addRow(new String[]{compras.getCPFCompra(),
                        compras.getNomeCliente(),
                        compras.getNomeCompra(),
                        compras.getCodigoProduto() + "",
                        compras.getCodigoCompra() + "",
                        compras.getDataCompra(),
                        compras.getQuantidadeC() + "",
                        compras.getValorCompra() + ""});
                }
            }
            jTableRelatorioCompra.setModel(modeloTableCompra);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultarPorCPFCompraActionPerformed

    private void jRadioDataHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDataHoraActionPerformed

        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        if (jRadioDataHora.isSelected() == true) {
            jRadioDataHora.setEnabled(false);
            jPesquisaDataHora.setEnabled(true);
            jConsultarPorDataHora.setEnabled(true);
            //Compra
            jRadioCodigoProduto.setEnabled(true);
            jPesquisaCodigoProduto.setEnabled(false);
            jConsultarPorCodigoProduto.setEnabled(false);
            jPesquisaCodigoProduto.setText("");
            //
            jRadioCpf.setEnabled(true);
            jRadioAllCompras.setEnabled(true);
            jCPFRelatorioCliente.setEnabled(false);
            jConsultarPorCPFCompra.setEnabled(false);
            jCPFRelatorioCliente.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioDataHoraActionPerformed

    private void jPesquisaCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisaCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisaCodigoProdutoActionPerformed

    private void jRadioAllComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAllComprasActionPerformed

        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        if (jRadioAllCompras.isSelected() == true) {
            jCPFRelatorioCliente.setEnabled(false);
            jConsultarPorCPFCompra.setEnabled(false);
            jPesquisaCodigoProduto.setEnabled(false);
            jConsultarPorDataHora.setEnabled(false);
            jRadioDataHora.setEnabled(true);
            jRadioCpf.setEnabled(true);
            jRadioAllCompras.setEnabled(false);
            jPesquisaCodigoProduto.setText("");
            jCPFRelatorioCliente.setText("");
            jPesquisaDataHora.setText("");
            jPesquisaDataHora.setEnabled(false);

            for (int i = 0; i < BancoListCompra.size(); i++) {
                Compra compras = BancoListCompra.get(i);
                modeloTableCompra.addRow(new String[]{compras.getCPFCompra(),
                    compras.getNomeCliente(),
                    compras.getNomeCompra(),
                    compras.getCodigoProduto() + "",
                    compras.getCodigoCompra() + "",
                    compras.getDataCompra(),
                    compras.getQuantidadeC() + "",
                    compras.getValorCompra() + ""});
            }
            jTableRelatorioCompra.setModel(modeloTableCompra);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioAllComprasActionPerformed

    private void jConsultarPorDataHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarPorDataHoraActionPerformed

        String dataHora = jPesquisaDataHora.getText();
        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        for (int i = 0; i < BancoListCompra.size(); i++) {
            Compra compras = BancoListCompra.get(i);
            if (compras.getDataCompra().toLowerCase().contains(dataHora.toLowerCase())) {
                modeloTableCompra.addRow(new String[]{compras.getCPFCompra(),
                    compras.getNomeCliente(),
                    compras.getNomeCompra(),
                    compras.getCodigoProduto() + "",
                    compras.getCodigoCompra() + "",
                    compras.getDataCompra(),
                    compras.getQuantidadeC() + "",
                    compras.getValorCompra() + ""});
            }
            jTableRelatorioCompra.setModel(modeloTableCompra);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultarPorDataHoraActionPerformed

    private void jRadioCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCodigoProdutoActionPerformed

        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        if (jRadioCodigoProduto.isSelected() == true) {
            jRadioCodigoProduto.setEnabled(false);
            jPesquisaCodigoProduto.setEnabled(true);
            jConsultarPorCodigoProduto.setEnabled(true);
            //Data&Hora
            jRadioDataHora.setEnabled(true);
            jPesquisaDataHora.setEnabled(false);
            jConsultarPorDataHora.setEnabled(false);
            jPesquisaDataHora.setText("");
            //CPF
            jRadioCpf.setEnabled(true);
            jConsultarPorCPFCompra.setEnabled(false);
            jCPFRelatorioCliente.setEnabled(false);
            jCPFRelatorioCliente.setText("");
            //AllCompras
            jRadioAllCompras.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCodigoProdutoActionPerformed

    private void jConsultarPorCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarPorCodigoProdutoActionPerformed

        Object[] colunas = {"CPF", "Nome Cliente", "Nome Compra", "Código Produto", "Código Compra", "Data&Hora", "Quantidade", "Valor"};
        DefaultTableModel modeloTableCompra = new DefaultTableModel();
        modeloTableCompra.setColumnIdentifiers(colunas);
        jTableRelatorioCompra.setModel(modeloTableCompra);

        int codigoProduto = Integer.parseInt(jPesquisaCodigoProduto.getText());
        for (int i = 0; i < BancoListCompra.size(); i++) {
            Compra compras = BancoListCompra.get(i);
            if (compras.getCodigoProduto() == codigoProduto) {
                modeloTableCompra.addRow(new String[]{compras.getCPFCompra(),
                    compras.getNomeCliente(),
                    compras.getNomeCompra(),
                    compras.getCodigoProduto() + "",
                    compras.getCodigoCompra() + "",
                    compras.getDataCompra(),
                    compras.getQuantidadeC() + "",
                    compras.getValorCompra() + ""});
            }
            jTableRelatorioCompra.setModel(modeloTableCompra);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultarPorCodigoProdutoActionPerformed

    private void jPesquisaDataHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisaDataHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisaDataHoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCompra;
    private javax.swing.JFormattedTextField jCPFRelatorioCliente;
    private javax.swing.JButton jCancelar;
    private javax.swing.JButton jConsultarPorCPFCompra;
    private javax.swing.JButton jConsultarPorCodigoProduto;
    private javax.swing.JButton jConsultarPorDataHora;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jImprimir;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jPesquisaCodigoProduto;
    private javax.swing.JTextField jPesquisaDataHora;
    private javax.swing.JRadioButton jRadioAllCompras;
    private javax.swing.JRadioButton jRadioCodigoProduto;
    private javax.swing.JRadioButton jRadioCpf;
    private javax.swing.JRadioButton jRadioDataHora;
    private javax.swing.JScrollPane jTableClientes;
    private javax.swing.JTable jTableRelatorioCompra;
    // End of variables declaration//GEN-END:variables
}
