/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.AdquirirServico;
import AllClass.Animal;
import AllClass.Cliente;
import AllClass.ServicoBasico;
import AllControlador.ControladorAdquirirServico;
import AllControlador.ControladorAnimal;
import AllControlador.ControladorCliente;
import AllControlador.ControladorServicoBasico;
import AllControlador.ControladorSuporte;
import static BancoDeDados.BancoPetshop.BancoListServicoBasico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felly
 */
public class TelaAderirServicoBasico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAderirServicoBasico
     */
    public TelaAderirServicoBasico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNomedoDono = new javax.swing.JTextField();
        jConsultCliente = new javax.swing.JButton();
        jIDdoAnimal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jNomedoAnimal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCPFDonoConsult = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAdquirirServicos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jServicosBasicosExibir = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jADDServico = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jIDcodigoServicoAdd = new javax.swing.JTextField();

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas NetBeans\\proje00235ety\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(0, 0, 900, 600);

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cliente e Animal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel6.setText("ID Animal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 20));

        jLabel9.setText("Nome:");
        jLabel9.setToolTipText("");
        jLabel9.setName(""); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 40, 20));

        jNomedoDono.setEditable(false);
        getContentPane().add(jNomedoDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 190, -1));

        jConsultCliente.setText("@");
        jConsultCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 40, 50));
        getContentPane().add(jIDdoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, -1));

        jLabel10.setText("Animal:");
        jLabel10.setToolTipText("");
        jLabel10.setName(""); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 50, 20));

        jNomedoAnimal.setEditable(false);
        getContentPane().add(jNomedoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 110, -1));

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Aderir serviço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 550, 49));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Serviços Adquiridos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        try {
            jCPFDonoConsult.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jCPFDonoConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, -1));

        jLabel11.setText("CPF:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 20));

        jAdquirirServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Serviço", "Nome", "Informação", "Data&Hora", "CPF", "ID Animal", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jAdquirirServicos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 710, 120));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 750, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dados do Animal:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jServicosBasicosExibir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Serviço", "Nome", "Informação", "Valor"
            }
        ));
        jScrollPane2.setViewportView(jServicosBasicosExibir);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 710, 100));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Selecione o Serviço Desejado:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jADDServico.setText("Adicionar");
        jADDServico.setEnabled(false);
        jADDServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jADDServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jADDServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 80, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("ID Serviço:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, 20));

        jIDcodigoServicoAdd.setEnabled(false);
        getContentPane().add(jIDcodigoServicoAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jConsultClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultClienteActionPerformed

        int codAnimal = Integer.parseInt(jIDdoAnimal.getText());
        String cpf = jCPFDonoConsult.getText();

        Animal testAnimal = ControladorAnimal.exibirAnimal(cpf, codAnimal);

        if (testAnimal != null) {
            jCPFDonoConsult.setEditable(false);
            jIDdoAnimal.setEditable(false);
            jNomedoDono.setEnabled(true);
            jNomedoAnimal.setEnabled(true);
            Cliente testCliente = ControladorCliente.exibirCliente(cpf);
            jNomedoDono.setText(testCliente.getNome());
            jNomedoAnimal.setText(testAnimal.getNomeA());
            jIDcodigoServicoAdd.setEnabled(true);
            jADDServico.setEnabled(true);

            Object[] colunas = {"ID Serviço", "Nome", "Informação", "Valor"}; //Falta modificar
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(colunas);
            jServicosBasicosExibir.setModel(modelo);
            for (int i = 0; i < BancoListServicoBasico.size(); i++) {
                ServicoBasico s = BancoListServicoBasico.get(i);
                modelo.addRow(new String[]{s.getS_CodigoS() + "",
                    s.getS_NomeS(),
                    s.getS_InforS(),
                    s.getS_ValorS() + ""});
            }
            jServicosBasicosExibir.setModel(modelo);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultClienteActionPerformed

    private void jADDServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jADDServicoActionPerformed

        String cpf = jCPFDonoConsult.getText();
        int codigoServico = Integer.parseInt(jIDcodigoServicoAdd.getText());

        ServicoBasico servico = ControladorServicoBasico.exibirServico(codigoServico);
        if (servico != null) {
            String nomeServico = servico.getS_NomeS();
            int codigoAnimal = Integer.parseInt(jIDdoAnimal.getText());
            double valorServico = servico.getS_ValorS();
            String nomeCliente = jNomedoDono.getText();
            String dataServico = ControladorSuporte.dateTime();
            AdquirirServico cadAdquirirServico = new AdquirirServico(nomeServico, nomeCliente, cpf, codigoAnimal, valorServico, codigoServico, dataServico);

            String testCadastroServico = ControladorAdquirirServico.adquirirServico(cadAdquirirServico);
            if (testCadastroServico.equals("1")) {

                Object[] colunas = {"ID Serviço", "Nome", "Informação", "Valor"};
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(colunas);
                jServicosBasicosExibir.setModel(modelo);
                for (int i = 0; i < BancoListServicoBasico.size(); i++) {
                    ServicoBasico s = BancoListServicoBasico.get(i);
                    modelo.addRow(new String[]{s.getS_CodigoS() + "",
                        s.getS_NomeS(),
                        s.getS_InforS(),
                        s.getS_ValorS() + ""});
                }
                jServicosBasicosExibir.setModel(modelo);
                
                jIDcodigoServicoAdd.setText("");

                //jAdquirirServicos
            } else {
                JOptionPane.showMessageDialog(null, testCadastroServico);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jADDServicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jADDServico;
    private javax.swing.JTable jAdquirirServicos;
    private javax.swing.JFormattedTextField jCPFDonoConsult;
    private javax.swing.JButton jConsultCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jIDcodigoServicoAdd;
    private javax.swing.JTextField jIDdoAnimal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomedoAnimal;
    private javax.swing.JTextField jNomedoDono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jServicosBasicosExibir;
    // End of variables declaration//GEN-END:variables
}
