/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllTelas;

import AllClass.Cliente;
import AllControlador.ControladorCliente;
import AllControlador.ControladorSuporte;
import static BancoDeDados.BancoPetshop.BancoListCliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felly
 */
public class TelaRelatorioCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorioCliente
     */
    public TelaRelatorioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRelatorioNomes = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTableClientes = new javax.swing.JScrollPane();
        jTableRelatorioCliente = new javax.swing.JTable();
        jCancelar = new javax.swing.JButton();
        jRadioAllClientes = new javax.swing.JRadioButton();
        jRadioNome = new javax.swing.JRadioButton();
        jRadioCpf = new javax.swing.JRadioButton();
        jPesquisaNome = new javax.swing.JTextField();
        jCPFRelatorioCliente = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jImprimir = new javax.swing.JButton();
        jConsultarPorNome = new javax.swing.JButton();
        jConsultarPorCPF1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        jLabel5.setText("Relatório Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jTableRelatorioCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Sexo", "Saldo", "N° de Animal"
            }
        ));
        jTableClientes.setViewportView(jTableRelatorioCliente);

        getContentPane().add(jTableClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 780, 240));

        jCancelar.setText("Sair");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 90, -1));

        groupRelatorioNomes.add(jRadioAllClientes);
        jRadioAllClientes.setText("All Clientes");
        jRadioAllClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAllClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAllClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 90, 30));

        groupRelatorioNomes.add(jRadioNome);
        jRadioNome.setText("Nome:");
        jRadioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 60, 30));

        groupRelatorioNomes.add(jRadioCpf);
        jRadioCpf.setText("CPF:");
        jRadioCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 50, 30));

        jPesquisaNome.setToolTipText("Digite o nome que deseja pesquisar \"Ex: Edypo Fellype\"");
        jPesquisaNome.setEnabled(false);
        jPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jPesquisaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 140, 30));

        try {
            jCPFRelatorioCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPFRelatorioCliente.setText("");
        jCPFRelatorioCliente.setEnabled(false);
        getContentPane().add(jCPFRelatorioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 120, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 800, 10));

        jImprimir.setText("Imprimir");
        jImprimir.setEnabled(false);
        getContentPane().add(jImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 530, 90, -1));

        jConsultarPorNome.setText("@");
        jConsultarPorNome.setToolTipText("");
        jConsultarPorNome.setEnabled(false);
        getContentPane().add(jConsultarPorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 30, 30));

        jConsultarPorCPF1.setText("@");
        jConsultarPorCPF1.setToolTipText("");
        jConsultarPorCPF1.setEnabled(false);
        jConsultarPorCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarPorCPF1ActionPerformed(evt);
            }
        });
        getContentPane().add(jConsultarPorCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 30, 30));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felly\\Desktop\\Programas Java\\PetshopSmart\\IMG\\TelaCadastro.png")); // NOI18N
        jLabel13.setToolTipText(""); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jDesktopPane1.add(jLabel13);
        jLabel13.setBounds(0, 0, 900, 600);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        ControladorSuporte.mudarTelaStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jRadioCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCpfActionPerformed

        Object[] colunas = {"Nome", "CPF", "Telefone", "Sexo", "Saldo", "N° de Animal"};
        DefaultTableModel modeloTableCliente = new DefaultTableModel();
        modeloTableCliente.setColumnIdentifiers(colunas);
        jTableRelatorioCliente.setModel(modeloTableCliente);
        if (jRadioCpf.isSelected() == true) {
            jRadioCpf.setEnabled(false);
            jRadioNome.setEnabled(true);
            jRadioAllClientes.setEnabled(true);
            jCPFRelatorioCliente.setEnabled(true);
            jConsultarPorCPF1.setEnabled(true);
            jPesquisaNome.setEnabled(false);
            jConsultarPorNome.setEnabled(false);
            jPesquisaNome.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCpfActionPerformed

    private void jPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisaNomeActionPerformed

    private void jConsultarPorCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarPorCPF1ActionPerformed

        String cpf;
        cpf = jCPFRelatorioCliente.getText();
        Object[] colunas = {"Nome", "CPF", "Telefone", "Sexo", "Saldo", "N° de Animal"};
        DefaultTableModel modeloTableCliente = new DefaultTableModel();
        modeloTableCliente.setColumnIdentifiers(colunas);
        jTableRelatorioCliente.setModel(modeloTableCliente);

        String testValidarCPF = ControladorCliente.validarCPF(cpf);
        if (testValidarCPF.equals("1")) {
            for (int i = 0; i < BancoListCliente.size(); i++) {
                Cliente c = BancoListCliente.get(i);
                if (c.getCpf().equals(cpf)) {
                    modeloTableCliente.addRow(new String[]{c.getNome(),
                        c.getCpf(),
                        c.getTelefone(),
                        c.getSexo(),
                        c.getSaldo() + "",
                        AllControlador.ControladorAnimal.quantAnimalCliente(cpf) + ""});
                }
            }
            jTableRelatorioCliente.setModel(modeloTableCliente);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jConsultarPorCPF1ActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jRadioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNomeActionPerformed

        Object[] colunas = {"Nome", "CPF", "Telefone", "Sexo", "Saldo", "N° de Animal"};
        DefaultTableModel modeloTableCliente = new DefaultTableModel();
        modeloTableCliente.setColumnIdentifiers(colunas);
        jTableRelatorioCliente.setModel(modeloTableCliente);

        if (jRadioNome.isSelected() == true) {
            jRadioNome.setEnabled(false);
            jRadioCpf.setEnabled(true);
            jRadioAllClientes.setEnabled(true);
            jCPFRelatorioCliente.setEnabled(false);
            jConsultarPorCPF1.setEnabled(false);
            jPesquisaNome.setEnabled(true);
            jConsultarPorNome.setEnabled(true);
            jCPFRelatorioCliente.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNomeActionPerformed

    private void jRadioAllClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAllClientesActionPerformed

        Object[] colunas = {"Nome", "CPF", "Telefone", "Sexo", "Saldo", "N° de Animal"};
        DefaultTableModel modeloTableCliente = new DefaultTableModel();
        modeloTableCliente.setColumnIdentifiers(colunas);
        jTableRelatorioCliente.setModel(modeloTableCliente);

        if (jRadioAllClientes.isSelected() == true) {
            jCPFRelatorioCliente.setEnabled(false);
            jConsultarPorCPF1.setEnabled(false);
            jPesquisaNome.setEnabled(false);
            jConsultarPorNome.setEnabled(false);
            jRadioNome.setEnabled(true);
            jRadioCpf.setEnabled(true);
            jRadioAllClientes.setEnabled(false);
            jPesquisaNome.setText("");
            jCPFRelatorioCliente.setText("");

            for (int i = 0; i < BancoListCliente.size(); i++) {
                Cliente c = BancoListCliente.get(i);
                modeloTableCliente.addRow(new String[]{c.getNome(),
                    c.getCpf(),
                    c.getTelefone(),
                    c.getSexo(),
                    c.getSaldo() + "",
                    AllControlador.ControladorAnimal.quantAnimalCliente(c.getCpf()) + ""});
            }
            jTableRelatorioCliente.setModel(modeloTableCliente);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioAllClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupRelatorioNomes;
    private javax.swing.JFormattedTextField jCPFRelatorioCliente;
    private javax.swing.JButton jCancelar;
    private javax.swing.JButton jConsultarPorCPF1;
    private javax.swing.JButton jConsultarPorNome;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jImprimir;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jPesquisaNome;
    private javax.swing.JRadioButton jRadioAllClientes;
    private javax.swing.JRadioButton jRadioCpf;
    private javax.swing.JRadioButton jRadioNome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jTableClientes;
    private javax.swing.JTable jTableRelatorioCliente;
    // End of variables declaration//GEN-END:variables
}
